site_name: "BDA"
site_author: "Luis García Bonifaz"
site_email: "l.garciabonifaz@edu.gva.es"
site_url: https://luisgarciabonifaz.github.io/BDA/

theme:
  name: material
  language: es
  custom_dir: overrides
  palette:
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: navy
      accent: deep orange

    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: navy
      accent: deep purple


extra_css:
  - css/custom.css
    
markdown_extensions:
  - attr_list          # Adds attribute lists to generated HTML
  - pymdownx.emoji:    # Para añadir iconos en el texto. Lista de iconos https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
 # - codehilite         # Syntax coloring for code blocks
  - tables
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition         # Adds boxes for Notes, Warnings, etc.
  - pymdownx.details
  - pymdownx.blocks.html
  - toc: 
#      permalink: true
      toc_depth: 3
  
copyright: "<a href='https://creativecommons.org/licenses/by/4.0/' target='_blank'>CC BY-NC-SA 4.0 (Reconeixement - NoComercial - CompartirIgual) © Luis Garcia Bonifaz</a>."

plugins:
  - git-revision-date-localized:
      type: date  # Puedes usar "datetime" si quieres tener fecha y hora
      locale: es  # Configura el idioma (opcional, "es" para español)

nav:
- "Inicio": 'index.md'
- Big Data Aplicado:
    - 'T1 - Fundamentos y Ecosistema Moderno de Big Data': T_01_Fundamentos_BigData/Fundamentos_BigData.md
    - 'T2 - Bases de Datos NoSQL': T_02_NoSQL/BD_NoSQL.md
    - 'T3 - Almacenamiento Moderno en Big Data': T_03_Almacenamiento_Moderno/Almacenamiento_Moderno_BigData.md
    - 'T4 - ETL con NiFi': T_04_NIFI/ETL_NiFi.md
    - 'T5 - Orquestacion': T_05_Orquestacion/Orquestacion_Flujos.md
    - 'T6 - Bussines Intelligence': T_06_Bussines_intelligence/BI_Visualizacion_Power_BI.md
    - 'T7 - Visualizacion Tiempo Real': T_07_Visualizacion_Tiempo_Real/Visualizacion_Tiempo_Real.md
